export default {
  CREATE_CATEGORY_FAIL: 'CATEGORY-001',
  DELETE_CATEGORY_FAIL: 'CATEGORY-002',
  UPDATE_CATEGORY_FAIL: 'CATEGORY-003',
  GET_CATEGORY_FAIL: 'CATEGORY-004',
  GET_ALL_CATEGORIES_FAIL: 'CATEGORY-005',
};
