export default {
  CREATE_PRODUCT_FAIL: 'PRODUCT-001',
  DELETE_PRODUCT_FAIL: 'PRODUCT-002',
  UPDATE_PRODUCT_FAIL: 'PRODUCT-003',
  GET_PRODUCT_FAIL: 'PRODUCT-004',
  GET_ALL_PRODUCTS_FAIL: 'PRODUCT-005',
};
